// -----------------------------------------------------------------------------
// Copyright 2020 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

#pragma once

// Project includes
#import "SGFCExitCode.h"

// System includes
#import <Foundation/NSObject.h>

// Forward declarations
@class SGFCDocument;

/// @brief The SGFCDocumentWriteResult class provides access to the result
/// of a write operation performed by SGFCDocumentWriteer.
///
/// @ingroup public-api
/// @ingroup sgfc-frontend
/// @ingroup document
///
/// SGFCDocumentWriteResult is immutable, i.e. once the
/// SGFCDocumentWriteResult object is constructed it cannot be changed.
///
/// Do @b NOT attempt to create an SGFCDocumentWriteResult object yourself,
/// instead always use the SGFCDocumentWriteResult object returned by one of
/// SGFCDocumentWriteer's write operations.
@interface SGFCDocumentWriteResult : NSObject
{
}

/// @brief Do @b NOT use this initializer
- (instancetype) init NS_UNAVAILABLE;

/// @brief Returns an SGFCExitCode value that best fits the result of the
/// write operation. The numeric value of the SGFCExitCode corresponds to
/// one of the exit codes of SGFC.
@property(nonatomic, readonly) SGFCExitCode exitCode;

/// @brief Returns a collection of SGFCMessage objects which together form
/// the parse result of the write operation. The messages appear in the order
/// in which they were generated by SGFC. The collection is empty if the
/// write operation did not generate any messages.
@property(nonatomic, strong, readonly) NSArray* parseResult;

/// @brief Prints the content of the SGFCDocumentWriteResult to stdout for
/// debugging purposes.
///
/// @todo Remove this prior to release.
- (void) debugPrintToConsole;

@end
