// -----------------------------------------------------------------------------
// Copyright 2020 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

#pragma once

// Project includes
#import "SGFCMessageType.h"

// System includes
#import <Foundation/NSObject.h>

/// @brief The SGFCMessage class represents a message that is generated
/// when SGF data is loaded and parsed, or when SGF data is saved. Most
/// messages are generated by SGFC, but there are a few error cases where
/// SgfcKit also generates messages. SGFCMessage objects are immutable.
///
/// When a message is generated by SGFC, the raw message text follows
/// formatting guidelines that are published in the SGFC documentation.
/// SgfcKit makes an effort to parse the raw message text so that it can
/// make the message content available to clients in a structured manner via
/// SGFCMessage.
///
/// @ingroup public-api
/// @ingroup sgfc-message
///
/// Do @b NOT attempt to create an SGFCMessage object yourself, instead
/// always use the SGFCMessage objects provided by other library objects (e.g.
/// an SGFCDocumentReaderResult instance).
@interface SGFCMessage : NSObject
{
}

/// @brief Do @b NOT use this initializer, it always raises
/// SGFCInvalidOperationException.
///
/// @exception SGFCInvalidOperationException Is raised whenever this initializer
/// is invoked.
- (id) init;

/// @brief Returns the message's identification number. Returns zero or a
/// positive number if the message was generated by SGFC. Returns a negative
/// number if the message was generated by SgfcKit.
///
/// Every message generated by SGFC has its own unique message ID. Consult
/// the SGFC documentation for a list of message IDs. SGFC calls them
/// "error codes". The exception is when SgfcKit is unable to determine
/// the message ID when it parses the raw message text - if that happens
/// SgfcKit sets the message ID to #SGFCUnknownSgfcMessageID.
///
/// Every message generated by SgfcKit also has its own unique message
/// ID. Documented constants for these are available in SGFCConstants.
/// Messages generated by SgfcKit are always fatal errors.
@property(nonatomic, readonly) NSInteger messageID;

/// @brief Returns the type of message.
@property(nonatomic, readonly) SGFCMessageType messageType;

/// @brief Returns the number of the line (1-based) in the parsed SGF data
/// that caused the message. Returns #SGFCInvalidLineNumber if
/// the message does not refer to a specific line in the SGF data (most
/// fatal errors, but also some errors and warnings).
@property(nonatomic, readonly) NSInteger lineNumber;

/// @brief Returns the number of the column (1-based) in the parsed SGF data
/// that caused the message. Returns #SGFCInvalidColumnNumber if
/// the message does not refer to a specific column in the SGF data (most
/// fatal errors, but also some errors and warnings).
@property(nonatomic, readonly) NSInteger columnNumber;

/// @brief Returns YES if the message describes a critical problem. Only
/// warning and error messages can be critical. Always returns NO for
/// fatal errors.
///
/// A critical problem indicates that the SGF content parsed by SGFC may be
/// severely damaged and that information may be lost if the parsed SGF data
/// is written.
@property(nonatomic, readonly, getter=isCriticalMessage) BOOL criticalMessage;

/// @brief Returns the message text.
///
/// For messages generated by SGFC this is the raw message text minus
/// the content that was parsed.
///
/// When the raw message text is parsed, consecutive whitespace characters
/// are condensed into a single space character. For messages generated by
/// SGFC this message text can therefore differ from the original raw
/// message text in the amount or kind of whitespace used.
@property(nonatomic, strong, readonly) NSString* messageText;

/// @brief Returns the raw message text exactly as it was generated by
/// SGFC. If the message was generated by SgfcKit this returns the same
/// value as messageText().
@property(nonatomic, strong, readonly) NSString* rawMessageText;

@end
