// -----------------------------------------------------------------------------
// Copyright 2024 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

#pragma once

// System includes
#import <Foundation/NSObjCRuntime.h>

/// @brief SGFCMessageID enumerates the message identification numbers that
/// an SGFCMessage object can have.
///
/// @ingroup public-api
///
/// Every enumerator has an underlying numeric value. Library clients should
/// not rely on a specific value as they can change without notice. The only
/// guarantee given is that positive values (including zero) are for messages
/// that are generated by SGFC, and negative values are for messages generated
/// by SgfcKit.
///
/// For messages that are generated by SGFC the numeric value underlying the
/// enumerator is equal to the message ID as documented by SGFC. Please
/// consult the SGFC documentation if in doubt about the meaning of a message.
/// SGFC calls them "error codes".
typedef NS_ENUM(NSInteger, SGFCMessageID)
{
  /// @name SGFC messages
  //@{
  /// @brief SGFC was invoked with an argument that is neither an option,
  /// an input file or an output file.
  ///
  /// This message cannot actually occur when using SGFC via SgfcKit.
  SGFCMessageIDUnknownCommand = 1,
  /// @brief SGFC was invoked with an argument that is not a supported short
  /// command line option.
  ///
  /// This message cannot actually occur when using SGFC via SgfcKit.
  SGFCMessageIDUnknownCommandLineOption = 2,
  /// @brief SGFC was unable to open the source file.
  SGFCMessageIDCouldNotOpenSourceFile = 3,
  /// @brief SGFC was unable to read the source file.
  SGFCMessageIDCouldNotReadSourceFile = 4,
  /// @brief SGFC was unable to allocate enough memory.
  SGFCMessageIDMemoryAllocationFailed = 5,
  /// @brief SGFC found what looks like SGF data before a game tree, i.e.
  /// before the character sequence "(;".
  SGFCMessageIDSgfDataBeforeGameTree = 6,
  /// @brief SGFC was unable to find any SGF data.
  SGFCMessageIDNoSgfData = 7,
  /// @brief SGFC found illegal characters in between SGF markup.
  SGFCMessageIDIllegalCharacters = 8,
  /// @brief SGFC found a variation that is missing the closing paranthesis.
  SGFCMessageIDVariationNestingIncomplete = 9,
  /// @brief SGFC parsed incomplete SGF content.
  SGFCMessageIDUnexpectedEndOfFile = 10,
  /// @brief SGFC found a property identifier that is too long. This may
  /// indicate that the content is not SGF.
  SGFCMessageIDPropertyIdentifierTooLong = 11,
  /// @brief SGFC found (and ignored) an empty variation.
  SGFCMessageIDEmptyVariationIgnored = 12,
  /// @brief SGFC found a property with more than one value although it can
  /// have only one value. SGFC deleted the surplus values.
  SGFCMessageIDSurplusValuesDeleted = 13,
  /// @brief SGFC found (and deleted) an illegal property value.
  SGFCMessageIDIllegalValueDeleted = 14,
  /// @brief SGFC found (and corrected) an illegal single property value.
  ///
  /// If the SGF content is in FF3 format this message has
  /// #SGFCMessageTypeWarning. If the SGF content is in FF4 format this
  /// message has #SGFCMessageTypeError.
  ///
  /// @see SGFCMessageIDIllegalComposedValueCorrected
  SGFCMessageIDIllegalSingleValueCorrected = 15,
  /// @brief SGFC found a property identifier that contains lowercase
  /// characters. This message is only generated for SGF content in FF4
  /// format.
  SGFCMessageIDPropertyIdentifierWithLowercaseCharacter = 16,
  /// @brief SGFC found (and deleted) an empty property value.
  ///
  /// Depending on the context this message has either
  /// #SGFCMessageTypeWarning or #SGFCMessageTypeError.
  SGFCMessageIDEmptyValueDeleted = 17,
  /// @brief SGFC found (and took action) a root property with an illegal
  /// value. The value may have been deleted or corrected.
  SGFCMessageIDIllegalRootPropertyValue = 18,
  /// @brief SGFC found a game type that is not Go. Move and position values
  /// are not checked.
  SGFCMessageIDGameIsNotGo = 19,
  /// @brief SGFC found (and ignored) a property without any values.
  SGFCMessageIDPropertyWithoutValuesIgnored = 20,
  /// @brief SGFC found (and ignored) an illegal variation start.
  SGFCMessageIDIllegalVariationStartIgnored = 21,
  /// @brief SGFC found a zero byte. The byte was replaced with a space
  /// character.
  SGFCMessageIDZeroByteDeleted = 22,
  /// @brief SGFC found a property that expects composed values but the
  /// actual values are one or more single values. SGFC deleted the single
  /// value(s).
  SGFCMessageIDNonComposedValueDeleted = 23,
  /// @brief SGFC found a move property in a game tree's root node and split
  /// the root node into two, with the move property being in the second node.
  SGFCMessageIDMoveInRootNodeSplit = 24,
  /// @brief SGFC found (and corrected) an illegal composed property value.
  ///
  /// @see SGFCMessageIDIllegalSingleValueCorrected
  SGFCMessageIDIllegalComposedValueCorrected = 25,
  /// @brief SGFC was unable to open the destination file.
  SGFCMessageIDCouldNotOpenDestinationFile = 26,
  /// @brief SGFC was unable to write the destination file.
  SGFCMessageIDCouldNotWriteDestinationFile = 27,
  /// @brief SGFC found (and deleted) a property that already exists.
  SGFCMessageIDDuplicatePropertyDeleted = 28,
  /// @brief SGFC found (and deleted) a property whose deletion was requested
  /// by the library client.
  ///
  /// The library client can request either specific properties to be deleted,
  /// or it can request the entire class of obsolete properties to be deleted.
  ///
  /// @see SGFCArgumentTypeDeletePropertyType.
  /// @see SGFCArgumentTypeDeleteObsoleteProperties.
  SGFCMessageIDRequestedPropertyDeleted = 29,
  /// @brief SGFC found a node that contains both setup and move properties.
  ///
  /// If the SGF content is in FF3 format this message has
  /// #SGFCMessageTypeWarning. If the SGF content is in FF4 format this
  /// message has #SGFCMessageTypeError.
  SGFCMessageIDMixedSetupAndMove = 30,
  /// @brief SGFC found a property with an identifier that consists of more
  /// than two uppercase characters.
  SGFCMessageIDLongPropertyIdentifier = 31,
  /// @brief SGFC found (and deleted) a root property in a node that is not
  /// the root node.
  SGFCMessageIDRootPropertyDeleted = 32,
  /// @brief SGFC found a game info property that is illegally formatted.
  ///
  /// If the SGF content is in FF3 format this message has
  /// #SGFCMessageTypeWarning. If the SGF content is in FF4 format this
  /// message has #SGFCMessageTypeError.
  SGFCMessageIDGameInfoPropertyWithIllegalFormat = 33,
  /// @brief SGFC did not save the SGF content because parsing generated
  /// one or more critical errors.
  ///
  /// This message cannot actually occur when using SGFC via SgfcKit.
  SGFCMessageIDNotSavedBecauseOfCriticalErrors = 34,
  /// @brief SGFC found (and deleted) an unknown (i.e. a custom) property.
  SGFCMessageIDUnknownPropertyDeleted = 35,
  /// @brief SGFC did not find a semicolon in front of what looks like a
  /// game tree.
  ///
  /// @see SGFCArgumentTypeBeginningOfSgfData.
  SGFCMessageIDMissingSemicolonAtGameTreeStart = 36,
  /// @brief SGFC found a node that contains moves by both the black and the
  /// white player. The node was split into two, with the black move and one
  /// with the white move.
  SGFCMessageIDBlackAndWhiteMoveSplit = 37,
  /// @brief SGFC found a position that is not unique, i.e. some combination
  /// of properties that operate on the same point with contradicting
  /// meaning (e.g. different markup or stones on the same point).
  SGFCMessageIDPositionNotUnique = 38,
  /// @brief SGFC found (and deleted) a property that adds a stone to the
  /// board (AB, AW, AE), but the addition is redundant because there is
  /// already a stone on the board in that location.
  SGFCMessageIDAddStoneDeleted = 39,
  /// @brief SGFC found a property that is not defined in the version of the
  /// SGF standard denoted by the FF property in the SGF content. The
  /// property may have been converted or even deleted.
  SGFCMessageIDPropertyNotDefinedInFF = 40,
  /// @brief SGFC found (and deleted) an annotation property whose value
  /// contradicts a previous property.
  SGFCMessageIDContradictingAnnotationDeleted = 41,
  /// @brief SGFC found a combination of certain properties and converted them
  /// to another property.
  ///
  /// Combinations of TE and BM get converted to DO and IT.
  ///
  /// If the SGF content is in FF3 format this message has
  /// #SGFCMessageTypeWarning. If the SGF content is in FF4 format this
  /// message has #SGFCMessageTypeError.
  SGFCMessageIDCombinationOfPropertiesConverted = 42,
  /// @brief SGFC found (and deleted) a move annotation property in a node
  /// that didn't also contain a move property.
  SGFCMessageIDMoveAnnotationDeleted = 43,
  /// @brief SGFC found (and deleted) a game info property outside of a
  /// game info node.
  ///
  /// If the SGF content is in FF3 format this message has
  /// #SGFCMessageTypeWarning. If the SGF content is in FF4 format this
  /// message has #SGFCMessageTypeError.
  SGFCMessageIDGameInfoDeleted = 44,
  /// @brief SGFC found different file formats in the SGF content.
  SGFCMessageIDDifferentFileFormats = 45,
  /// @brief SGFC found an unknown file format in the SGF content. SGFC can
  /// handle only file formats up to FF4.
  SGFCMessageIDUnknownFileFormat = 46,
  /// @brief SGFC found (and corrected) an SZ property with two values
  /// defining a rectangular board, but the two values were the same, so
  /// SGFC corrected this to an SZ property with a single value defining
  /// a square board.
  SGFCMessageIDSquareBoardSizeCorrected = 47,
  /// @brief SGFC was invoked without a source file argument.
  ///
  /// This message cannot actually occur when using SGFC via SgfcKit.
  SGFCMessageIDSourceFileNotSpecified = 48,
  /// @brief SGFC was invoked with an argument that takes a parameter, but
  /// the specified parameter is illegal for the argument.
  SGFCMessageIDBadCommandLineOptionParameter = 49,
  /// @brief SGFC found (and corrected) a board size property with a value
  /// that is too large.
  SGFCMessageIDTooLargeBoardSizeCorrected = 50,
  /// @brief SGFC found a feature that is not defined in the particular file
  /// format of the SGF content.
  SGFCMessageIDUsedFeatureNotDefinedInFileFormat = 51,
  /// @brief SGFC found one of various error cases related to the VW property.
  /// The exact problem is in the message text.
  SGFCMessageIDViewError = 52,
  /// @brief SGFC found different game types in the SGF content.
  SGFCMessageIDDifferentGameTypes = 53,
  /// @brief SGFC found (and deleted) one or more values not associated with
  /// any property.
  SGFCMessageIDValuesWithoutPropertyDeleted = 54,
  /// @brief SGFC found (and deleted) an empty node.
  ///
  /// @see SGFCArgumentTypeDeleteEmptyNodes.
  SGFCMessageIDEmptyNodeDeleted = 55,
  /// @brief SGFC found what could possibly be a wrong variation level.
  /// It was unable to take corrective action.
  SGFCMessageIDVariationLevelNotCorrected = 56,
  /// @brief SGFC found a wrong variation level. It was able to take
  /// corrective action.
  SGFCMessageIDVariationLevelCorrected = 57,
  /// @brief SGFC found a forbidden move that played a stone on a point that
  /// is already occupied by another stone.
  SGFCMessageIDForbiddenMove = 58,
  /// @brief SGFC found (and deleted/converted) an obsolete KI property.
  SGFCMessageIDIntegerKomiDeleted = 59,
  /// @brief SGFC found more than one game tree in the SGF content.
  ///
  /// @see SGFCArgumentTypeEnableRestrictiveChecking.
  SGFCMessageIDMoreThanOneGameTree = 60,
  /// @brief SGFC found a HA property whose value differs from the number of
  /// stones that were set up with setup properties.
  ///
  /// @see SGFCArgumentTypeEnableRestrictiveChecking.
  SGFCMessageIDHandicapDiffersFromSetup = 61,
  /// @brief SGFC found setup properties in a node that is not the root node.
  ///
  /// @see SGFCArgumentTypeEnableRestrictiveChecking.
  SGFCMessageIDSetupStonesOutsideRootNode = 62,
  /// @brief SGFC found two successive moves that have the same color.
  ///
  /// @see SGFCArgumentTypeEnableRestrictiveChecking.
  SGFCMessageIDTwoMovesWithSameColor = 63,
  /// @brief SGFC was unable to reorder variations because there were too many
  /// variations in the SGF content.
  SGFCMessageIDVariationReorderFailed = 64,
  /// @brief SGFC found a pass move in the new FF4 style in SGF content that
  /// has an older file format.
  SGFCMessageIDNewStylePassMove = 65,
  /// @brief SGFC found (and fixed) a node that was not in any variation.
  SGFCMessageIDNodeNotInVariation = 66,
  /// @brief SGFC found (and corrected) an illegal variation start.
  SGFCMessageIDIllegalVariationStartCorrected = 67,
  /// @brief SGFC was invoked with an argument that is not a supported long
  /// command line option.
  ///
  /// This message cannot actually occur when using SGFC via SgfcKit.
  SGFCMessageIDUnknownLongCommandLineOption = 68,
  /// @brief An unknown encoding was specified for one of the encoding
  /// argument types.
  ///
  /// @see SGFCArgumentTypeDefaultEncoding
  /// @see SGFCArgumentTypeForcedEncoding
  SGFCMessageIDUnknownEncodingInArgument = 69,
  /// @brief SGFC encountered an unknown iconv error during the encoding
  /// phase. This is an internal error which cannot be handled gracefully.
  SGFCMessageIDUnknownIconvError = 70,

  /// @brief SGFC encountered one or more errors during the encoding phase.
  /// A typical example is that a byte sequence was encountered which is
  /// illegal according to the encoding to be used. The error was handled by
  /// ignoring the faulty bytes, but the resulting SGF content might well be
  /// unusable.
  SGFCMessageIDEncodingErrorsDetected = 71,
  /// @brief An unknown encoding was specified in the SGF content (i.e. as
  /// value of a CA property). The error is handled by falling back to the
  /// default encoding.
  SGFCMessageIDUnknownEncodingInSgfContent = 72,
  /// @brief SGFC failed to detect the encoding that it should use. This
  /// error can be prevented only by specifying a forced encoding to use.
  ///
  /// @see SGFCArgumentTypeForcedEncoding
  SGFCMessageIDEncodingDetectionFailed = 73,
  /// @brief SGFC found different encodings in the same SGF content. This
  /// happens when SGF content has multiple game trees and at least two of
  /// them specify a different CA property value.
  ///
  /// This message occurs when encoding modes 2 or 3 are used. The message
  /// is a critical warning only, so unlike
  /// #SGFCMessageIDSgfContentHasDifferentEncodingsFatal the library client
  /// will be able to process the result. If the encodings used are multibyte
  /// encodings there is still a good chance that the encoding phase of SGFC
  /// will produce an unusable result.
  ///
  /// @see SGFCArgumentTypeEncodingMode
  SGFCMessageIDSgfContentHasDifferentEncodings = 74,
  /// @brief SGFC found different encodings in the same SGF content. This
  /// happens when SGF content has multiple game trees and at least two of
  /// them specify a different CA property value.
  ///
  /// This message occurs when encoding mode 1 is used. The message is a
  /// fatal error because the encoding phase of SGFC is practically
  /// guaranteed to produce an unusable result. The library client must use
  /// encoding modes 2 or 3 to process the SGF content. Even then SGFC will
  /// generate #SGFCMessageIDSgfContentHasDifferentEncodings.
  ///
  /// @see SGFCArgumentTypeEncodingMode
  SGFCMessageIDSgfContentHasDifferentEncodingsFatal = 75,
  /// @brief Indicates that the message was generated by SGFC, but SgfcKit
  /// was unable to determine the message ID.
  ///
  /// This message ID is a positive number in order to satisfy the guarantee
  /// that SGFC-generated messages always have message IDs >= 0. SgfcKit
  /// strives to use a number that is not in the list of message IDs that are
  /// documented by SGFC.
  SGFCMessageIDUnknownSgfcMessageID = 0x7FFFFFFF,
  //@}

  // ----------------------------------------------------------------------

  /// @name SgfcKit messages
  //@{
  /// @brief Indicates a message without a valid ID. If a message with this
  /// ID is seen by a library client this indicates a coding error in
  /// SgfcKit.
  SGFCMessageIDInvalidMessageID = -1,
  /// @brief Indicates that a fatal error occurred when SGFC parsed arguments,
  /// but SgfcKit was unable to obtain the fatal error message from SGFC.
  SGFCMessageIDParseArgumentError = -2,
  /// @brief Indicates a fatal error that occurred while SgfcKit attempted
  /// to save a piece of SGF content to the filesystem.
  SGFCMessageIDSaveSgfContentToFilesystemError = -3,
  /// @brief Indicates a fatal error that occurred while SgfcKit attempted
  /// to read a piece of SGF content from the filesystem.
  SGFCMessageIDReadSgfContentFromFilesystemError = -4,
  /// @brief Indicates a fatal error that occurred while SgfcKit attempted
  /// to delete a file in the filesystem.
  SGFCMessageIDDeleteFileError = -5,
  /// @brief Indicates a fatal error because memory allocation failed in SGFC.
  SGFCMessageIDOutOfMemoryError = -6,
  /// @brief Indicates a fatal error that occurred while SgfcKit attempted
  /// to parse SGF content in order to generate a document.
  ///
  /// This is likely to be a data-related issue.
  SGFCMessageIDParseSgfContentError = -7,
  /// @brief Indicates a fatal interfacing error between SgfcKit and SGFC.
  ///
  /// Problems can range from simple (but fundamental) things such as an
  /// unexpected @e nil in one of the SGFC data structures, to more
  /// complex data-related issues such as when SGFC and SgfcKit disagree
  /// about the data type(s) of a property value.
  ///
  /// The message text is technical and unlikely to have any meaning for an
  /// end user.
  SGFCMessageIDSGFCInterfacingError = -8,
  //@}
};
