// -----------------------------------------------------------------------------
// Copyright 2020 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

// TODO Cleanup unneeded stuff

// Project includes
#import "../include/SGFCConstants.h"
//#import "SgfcPrivateConstants.h"

// System includes
#import <Foundation/NSString.h>

NSString* SGFCLibraryName = @"libsgfc++";
NSString* SGFCLibraryVersion = @"0.1 (alpha)";
NSString* SGFCSgfcVersion = @"1.18";

// Must be a positive number to indicate that the message was generated by
// SGFC.
//const int SGFCUnknownSgfcMessageID = std::numeric_limits<int>::max();
//const int SGFCInvalidMessageID = -1;
//const int SGFCParseArgumentErrorMessageID = -2;
//const int SGFCSaveSgfContentToFilesystemErrorMessageID = -3;
//const int SGFCReadSgfContentFromFilesystemErrorMessageID = -4;
//const int SGFCDeleteFileErrorMessageID = -5;
//
//const int SGFCInvalidLineNumber = -1;
//const int SGFCInvalidColumnNumber = -1;

//NSString* SGFCNoneValueString = SgfcPrivateConstants::EmptyString;
NSString* SGFCDoubleNormalString = @"1";
NSString* SGFCDoubleEmphasizedString = @"2";
NSString* SGFCColorBlackString = @"B";
NSString* SGFCColorWhiteString = @"W";
//NSString* SGFCGoMovePassString = SgfcPrivateConstants::EmptyString;

//const std::map<NSString*, SGFCPropertyType> SGFCPropertyNameToPropertyTypeMap =
//{
//  { "B", SGFCPropertyTypeB },
//  { "KO", SGFCPropertyTypeKO },
//  { "MN", SGFCPropertyTypeMN },
//  { "W", SGFCPropertyTypeW },
//  { "AB", SGFCPropertyTypeAB },
//  { "AE", SGFCPropertyTypeAE },
//  { "AW", SGFCPropertyTypeAW },
//  { "PL", SGFCPropertyTypePL },
//  { "C", SGFCPropertyTypeC },
//  { "DM", SGFCPropertyTypeDM },
//  { "GB", SGFCPropertyTypeGB },
//  { "GW", SGFCPropertyTypeGW },
//  { "HO", SGFCPropertyTypeHO },
//  { "N", SGFCPropertyTypeN },
//  { "UC", SGFCPropertyTypeUC },
//  { "V", SGFCPropertyTypeV },
//  { "BM", SGFCPropertyTypeBM },
//  { "DO", SGFCPropertyTypeDO },
//  { "IT", SGFCPropertyTypeIT },
//  { "TE", SGFCPropertyTypeTE },
//  { "AR", SGFCPropertyTypeAR },
//  { "CR", SGFCPropertyTypeCR },
//  { "DD", SGFCPropertyTypeDD },
//  { "LB", SGFCPropertyTypeLB },
//  { "LN", SGFCPropertyTypeLN },
//  { "MA", SGFCPropertyTypeMA },
//  { "SL", SGFCPropertyTypeSL },
//  { "SQ", SGFCPropertyTypeSQ },
//  { "TR", SGFCPropertyTypeTR },
//  { "AP", SGFCPropertyTypeAP },
//  { "CA", SGFCPropertyTypeCA },
//  { "FF", SGFCPropertyTypeFF },
//  { "GM", SGFCPropertyTypeGM },
//  { "ST", SGFCPropertyTypeST },
//  { "SZ", SGFCPropertyTypeSZ },
//  { "AN", SGFCPropertyTypeAN },
//  { "BR", SGFCPropertyTypeBR },
//  { "BT", SGFCPropertyTypeBT },
//  { "CP", SGFCPropertyTypeCP },
//  { "DT", SGFCPropertyTypeDT },
//  { "EV", SGFCPropertyTypeEV },
//  { "GN", SGFCPropertyTypeGN },
//  { "GC", SGFCPropertyTypeGC },
//  { "ON", SGFCPropertyTypeON },
//  { "OT", SGFCPropertyTypeOT },
//  { "PB", SGFCPropertyTypePB },
//  { "PC", SGFCPropertyTypePC },
//  { "PW", SGFCPropertyTypePW },
//  { "RE", SGFCPropertyTypeRE },
//  { "RO", SGFCPropertyTypeRO },
//  { "RU", SGFCPropertyTypeRU },
//  { "SO", SGFCPropertyTypeSO },
//  { "TM", SGFCPropertyTypeTM },
//  { "US", SGFCPropertyTypeUS },
//  { "WR", SGFCPropertyTypeWR },
//  { "WT", SGFCPropertyTypeWT },
//  { "BL", SGFCPropertyTypeBL },
//  { "OB", SGFCPropertyTypeOB },
//  { "OW", SGFCPropertyTypeOW },
//  { "WL", SGFCPropertyTypeWL },
//  { "FG", SGFCPropertyTypeFG },
//  { "PM", SGFCPropertyTypePM },
//  { "VW", SGFCPropertyTypeVW },
//  { "BS", SGFCPropertyTypeBS },
//  { "CH", SGFCPropertyTypeCH },
//  { "EL", SGFCPropertyTypeEL },
//  { "EX", SGFCPropertyTypeEX },
//  { "ID", SGFCPropertyTypeID },
//  { "L", SGFCPropertyTypeL },
//  { "LT", SGFCPropertyTypeLT },
//  { "M", SGFCPropertyTypeM },
//  { "OM", SGFCPropertyTypeOM },
//  { "OP", SGFCPropertyTypeOP },
//  { "OV", SGFCPropertyTypeOV },
//  { "RG", SGFCPropertyTypeRG },
//  { "SC", SGFCPropertyTypeSC },
//  { "SE", SGFCPropertyTypeSE },
//  { "SI", SGFCPropertyTypeSI },
//  { "TC", SGFCPropertyTypeTC },
//  { "WS", SGFCPropertyTypeWS },
//  { "HA", SGFCPropertyTypeHA },
//  { "KM", SGFCPropertyTypeKM },
//  { "TB", SGFCPropertyTypeTB },
//  { "TW", SGFCPropertyTypeTW },
//  { "CO", SGFCPropertyTypeCO },
//  { "CV", SGFCPropertyTypeCV },
//  { "DI", SGFCPropertyTypeDI },
//  { "MI", SGFCPropertyTypeMI },
//  { "IY", SGFCPropertyTypeIY },
//  { "SU", SGFCPropertyTypeSU },
//  { "IS", SGFCPropertyTypeIS },
//  { "AA", SGFCPropertyTypeAA },
//  { "BO", SGFCPropertyTypeBO },
//  { "WO", SGFCPropertyTypeWO },
//  { "NP", SGFCPropertyTypeNP },
//  { "NR", SGFCPropertyTypeNR },
//  { "NS", SGFCPropertyTypeNS },
//  { "CS", SGFCPropertyTypeCS },
//  { "MS", SGFCPropertyTypeMS },
//  { "SS", SGFCPropertyTypeSS },
//  { "TS", SGFCPropertyTypeTS },
//  { "RP", SGFCPropertyTypeRP },
//  { "AS", SGFCPropertyTypeAS },
//  { "IP", SGFCPropertyTypeIP },
//  { "KI", SGFCPropertyTypeKI },
//};

//const std::map<SGFCPropertyType, NSString*> SGFCPropertyTypeToPropertyNameMap =
//{
//  { SGFCPropertyTypeB, "B" },
//  { SGFCPropertyTypeKO, "KO" },
//  { SGFCPropertyTypeMN, "MN" },
//  { SGFCPropertyTypeW, "W" },
//  { SGFCPropertyTypeAB, "AB" },
//  { SGFCPropertyTypeAE, "AE" },
//  { SGFCPropertyTypeAW, "AW" },
//  { SGFCPropertyTypePL, "PL" },
//  { SGFCPropertyTypeC, "C" },
//  { SGFCPropertyTypeDM, "DM" },
//  { SGFCPropertyTypeGB, "GB" },
//  { SGFCPropertyTypeGW, "GW" },
//  { SGFCPropertyTypeHO, "HO" },
//  { SGFCPropertyTypeN, "N" },
//  { SGFCPropertyTypeUC, "UC" },
//  { SGFCPropertyTypeV, "V" },
//  { SGFCPropertyTypeBM, "BM" },
//  { SGFCPropertyTypeDO, "DO" },
//  { SGFCPropertyTypeIT, "IT" },
//  { SGFCPropertyTypeTE, "TE" },
//  { SGFCPropertyTypeAR, "AR" },
//  { SGFCPropertyTypeCR, "CR" },
//  { SGFCPropertyTypeDD, "DD" },
//  { SGFCPropertyTypeLB, "LB" },
//  { SGFCPropertyTypeLN, "LN" },
//  { SGFCPropertyTypeMA, "MA" },
//  { SGFCPropertyTypeSL, "SL" },
//  { SGFCPropertyTypeSQ, "SQ" },
//  { SGFCPropertyTypeTR, "TR" },
//  { SGFCPropertyTypeAP, "AP" },
//  { SGFCPropertyTypeCA, "CA" },
//  { SGFCPropertyTypeFF, "FF" },
//  { SGFCPropertyTypeGM, "GM" },
//  { SGFCPropertyTypeST, "ST" },
//  { SGFCPropertyTypeSZ, "SZ" },
//  { SGFCPropertyTypeAN, "AN" },
//  { SGFCPropertyTypeBR, "BR" },
//  { SGFCPropertyTypeBT, "BT" },
//  { SGFCPropertyTypeCP, "CP" },
//  { SGFCPropertyTypeDT, "DT" },
//  { SGFCPropertyTypeEV, "EV" },
//  { SGFCPropertyTypeGN, "GN" },
//  { SGFCPropertyTypeGC, "GC" },
//  { SGFCPropertyTypeON, "ON" },
//  { SGFCPropertyTypeOT, "OT" },
//  { SGFCPropertyTypePB, "PB" },
//  { SGFCPropertyTypePC, "PC" },
//  { SGFCPropertyTypePW, "PW" },
//  { SGFCPropertyTypeRE, "RE" },
//  { SGFCPropertyTypeRO, "RO" },
//  { SGFCPropertyTypeRU, "RU" },
//  { SGFCPropertyTypeSO, "SO" },
//  { SGFCPropertyTypeTM, "TM" },
//  { SGFCPropertyTypeUS, "US" },
//  { SGFCPropertyTypeWR, "WR" },
//  { SGFCPropertyTypeWT, "WT" },
//  { SGFCPropertyTypeBL, "BL" },
//  { SGFCPropertyTypeOB, "OB" },
//  { SGFCPropertyTypeOW, "OW" },
//  { SGFCPropertyTypeWL, "WL" },
//  { SGFCPropertyTypeFG, "FG" },
//  { SGFCPropertyTypePM, "PM" },
//  { SGFCPropertyTypeVW, "VW" },
//  { SGFCPropertyTypeBS, "BS" },
//  { SGFCPropertyTypeCH, "CH" },
//  { SGFCPropertyTypeEL, "EL" },
//  { SGFCPropertyTypeEX, "EX" },
//  { SGFCPropertyTypeID, "ID" },
//  { SGFCPropertyTypeL, "L" },
//  { SGFCPropertyTypeLT, "LT" },
//  { SGFCPropertyTypeM, "M" },
//  { SGFCPropertyTypeOM, "OM" },
//  { SGFCPropertyTypeOP, "OP" },
//  { SGFCPropertyTypeOV, "OV" },
//  { SGFCPropertyTypeRG, "RG" },
//  { SGFCPropertyTypeSC, "SC" },
//  { SGFCPropertyTypeSE, "SE" },
//  { SGFCPropertyTypeSI, "SI" },
//  { SGFCPropertyTypeTC, "TC" },
//  { SGFCPropertyTypeWS, "WS" },
//  { SGFCPropertyTypeHA, "HA" },
//  { SGFCPropertyTypeKM, "KM" },
//  { SGFCPropertyTypeTB, "TB" },
//  { SGFCPropertyTypeTW, "TW" },
//  { SGFCPropertyTypeCO, "CO" },
//  { SGFCPropertyTypeCV, "CV" },
//  { SGFCPropertyTypeDI, "DI" },
//  { SGFCPropertyTypeMI, "MI" },
//  { SGFCPropertyTypeIY, "IY" },
//  { SGFCPropertyTypeSU, "SU" },
//  { SGFCPropertyTypeIS, "IS" },
//  { SGFCPropertyTypeAA, "AA" },
//  { SGFCPropertyTypeBO, "BO" },
//  { SGFCPropertyTypeWO, "WO" },
//  { SGFCPropertyTypeNP, "NP" },
//  { SGFCPropertyTypeNR, "NR" },
//  { SGFCPropertyTypeNS, "NS" },
//  { SGFCPropertyTypeCS, "CS" },
//  { SGFCPropertyTypeMS, "MS" },
//  { SGFCPropertyTypeSS, "SS" },
//  { SGFCPropertyTypeTS, "TS" },
//  { SGFCPropertyTypeRP, "RP" },
//  { SGFCPropertyTypeAS, "AS" },
//  { SGFCPropertyTypeIP, "IP" },
//  { SGFCPropertyTypeKI, "KI" },
//};

//const std::map<SGFCNumber, SGFCGameType> SGFCGameTypeAsNumberToGameTypeMap =
//{
//  { 1, SGFCGameTypeGo },
//  { 2, SGFCGameTypeOthello },
//  { 3, SGFCGameTypeChess },
//  { 4, SGFCGameTypeGomokuAndRenju },
//  { 5, SGFCGameTypeNineMensMorris },
//  { 6, SGFCGameTypeBackgammon },
//  { 7, SGFCGameTypeChineseChess },
//  { 8, SGFCGameTypeShogi },
//  { 9, SGFCGameTypeLinesOfAction },
//  { 10, SGFCGameTypeAtaxx },
//  { 11, SGFCGameTypeHex },
//  { 12, SGFCGameTypeJungle },
//  { 13, SGFCGameTypeNeutron },
//  { 14, SGFCGameTypePhilosophersFootball },
//  { 15, SGFCGameTypeQuadrature },
//  { 16, SGFCGameTypeTrax },
//  { 17, SGFCGameTypeTantrix },
//  { 18, SGFCGameTypeAmazons },
//  { 19, SGFCGameTypeOcti },
//  { 20, SGFCGameTypeGess },
//  { 21, SGFCGameTypeTwixt },
//  { 22, SGFCGameTypeZertz },
//  { 23, SGFCGameTypePlateau },
//  { 24, SGFCGameTypeYinsh },
//  { 25, SGFCGameTypePunct },
//  { 26, SGFCGameTypeGobblet },
//  { 27, SGFCGameTypeHive },
//  { 28, SGFCGameTypeExxit },
//  { 29, SGFCGameTypeHnefatal },
//  { 30, SGFCGameTypeKuba },
//  { 31, SGFCGameTypeTripples },
//  { 32, SGFCGameTypeChase },
//  { 33, SGFCGameTypeTumblingDown },
//  { 34, SGFCGameTypeSahara },
//  { 35, SGFCGameTypeByte },
//  { 36, SGFCGameTypeFocus },
//  { 37, SGFCGameTypeDvonn },
//  { 38, SGFCGameTypeTamsk },
//  { 39, SGFCGameTypeGipf },
//  { 40, SGFCGameTypeKropki },
//};

//const std::map<SGFCGameType, SGFCNumber> SGFCGameTypeToGameTypeAsNumberMap =
//{
//  { SGFCGameTypeGo, 1 },
//  { SGFCGameTypeOthello, 2 },
//  { SGFCGameTypeChess, 3 },
//  { SGFCGameTypeGomokuAndRenju, 4 },
//  { SGFCGameTypeNineMensMorris, 5 },
//  { SGFCGameTypeBackgammon, 6 },
//  { SGFCGameTypeChineseChess, 7 },
//  { SGFCGameTypeShogi, 8 },
//  { SGFCGameTypeLinesOfAction, 9 },
//  { SGFCGameTypeAtaxx, 10 },
//  { SGFCGameTypeHex, 11 },
//  { SGFCGameTypeJungle, 12 },
//  { SGFCGameTypeNeutron, 13 },
//  { SGFCGameTypePhilosophersFootball, 14 },
//  { SGFCGameTypeQuadrature, 15 },
//  { SGFCGameTypeTrax, 16 },
//  { SGFCGameTypeTantrix, 17 },
//  { SGFCGameTypeAmazons, 18 },
//  { SGFCGameTypeOcti, 19 },
//  { SGFCGameTypeGess, 20 },
//  { SGFCGameTypeTwixt, 21 },
//  { SGFCGameTypeZertz, 22 },
//  { SGFCGameTypePlateau, 23 },
//  { SGFCGameTypeYinsh, 24 },
//  { SGFCGameTypePunct, 25 },
//  { SGFCGameTypeGobblet, 26 },
//  { SGFCGameTypeHive, 27 },
//  { SGFCGameTypeExxit, 28 },
//  { SGFCGameTypeHnefatal, 29 },
//  { SGFCGameTypeKuba, 30 },
//  { SGFCGameTypeTripples, 31 },
//  { SGFCGameTypeChase, 32 },
//  { SGFCGameTypeTumblingDown, 33 },
//  { SGFCGameTypeSahara, 34 },
//  { SGFCGameTypeByte, 35 },
//  { SGFCGameTypeFocus, 36 },
//  { SGFCGameTypeDvonn, 37 },
//  { SGFCGameTypeTamsk, 38 },
//  { SGFCGameTypeGipf, 39 },
//  { SGFCGameTypeKropki, 40 },
//};

const SGFCGameType SGFCDefaultGameType = SGFCGameTypeGo;
const SGFCBoardSize SGFCBoardSizeMinimum =  SGFCBoardSizeMake(1, 1);
const SGFCBoardSize SGFCBoardSizeMaximumGo = SGFCBoardSizeMake(52, 52);
const SGFCBoardSize SGFCBoardSizeDefaultGo = SGFCBoardSizeMake(19, 19);
const SGFCBoardSize SGFCBoardSizeDefaultChess = SGFCBoardSizeMake(8, 8);

NSExceptionName const SGFCInvalidOperationException = @"SGFCInvalidOperationException";
NSExceptionName const SGFCDocumentStructureException = @"SGFCDocumentStructureException";
NSExceptionName const SGFCNotImplementedException = @"SGFCNotImplementedException";

const SGFCBoardSize SGFCBoardSizeNone = SGFCBoardSizeMake(-1, -1);
const SGFCBoardSize SGFCBoardSizeInvalid = SGFCBoardSizeMake(-2, -2);
