set (
  SOURCES
  document/typedpropertyvalue/SGFCColorPropertyValue.mm
  document/typedpropertyvalue/SGFCDoublePropertyValue.mm
  document/typedpropertyvalue/SGFCMovePropertyValue.mm
  document/typedpropertyvalue/SGFCNumberPropertyValue.mm
  document/typedpropertyvalue/SGFCPointPropertyValue.mm
  document/typedpropertyvalue/SGFCRealPropertyValue.mm
  document/typedpropertyvalue/SGFCSimpleTextPropertyValue.mm
  document/typedpropertyvalue/SGFCStonePropertyValue.mm
  document/typedpropertyvalue/SGFCTextPropertyValue.mm
  document/SGFCComposedPropertyValue.mm
  document/SGFCDocument.mm
  document/SGFCGame.mm
  document/SGFCNode.mm
  document/SGFCProperty.mm
  document/SGFCSinglePropertyValue.mm
  document/SGFCTreeBuilder.mm
  factory/SGFCKitFactory.mm
  factory/SGFCPropertyFactory.mm
  factory/SGFCPropertyValueFactory.mm
  game/SGFCBoardSize.mm
  sgfc/argument/SGFCArgument.mm
  sgfc/argument/SGFCArguments.mm
  SGFCConstants.mm
  SGFCExceptionUtility.mm
  SGFCMappingUtility.mm
  SGFCPrivateConstants.mm
  ${SOURCES_LIST_FILE_NAME}
)

set (
  HEADERS_PRIVATE
  interface/internal/SGFCArgumentInternalAdditions.h
  interface/internal/SGFCArgumentsInternalAdditions.h
  interface/internal/SGFCComposedPropertyValueInternalAdditions.h
  interface/internal/SGFCGameInternalAdditions.h
  interface/internal/SGFCNodeInternalAdditions.h
  interface/internal/SGFCPropertyInternalAdditions.h
  interface/internal/SGFCPropertyValueInternal.h
  interface/internal/SGFCSinglePropertyValueInternalAdditions.h
  interface/internal/SGFCTreeBuilderInternalAdditions.h
  SGFCExceptionUtility.h
  SGFCMappingUtility.h
  SGFCPrivateConstants.h
)

set (
  HEADERS_PUBLIC
  ../include/SGFCArgument.h
  ../include/SGFCArguments.h
  ../include/SGFCArgumentType.h
  ../include/SGFCBoardSize.h
  ../include/SGFCColor.h
  ../include/SGFCColorPropertyValue.h
  ../include/SGFCComposedPropertyValue.h
  ../include/SGFCConstants.h
  ../include/SGFCCoordinateSystem.h
  ../include/SGFCDocument.h
  ../include/SGFCDouble.h
  ../include/SGFCDoublePropertyValue.h
  ../include/SGFCGame.h
  ../include/SGFCGameType.h
  ../include/SGFCGoPointNotation.h
  ../include/SGFCMovePropertyValue.h
  ../include/SGFCKitFactory.h
  ../include/SGFCNode.h
  ../include/SGFCNumberPropertyValue.h
  ../include/SGFCPointPropertyValue.h
  ../include/SGFCProperty.h
  ../include/SGFCPropertyFactory.h
  ../include/SGFCPropertyType.h
  ../include/SGFCPropertyValue.h
  ../include/SGFCPropertyValueFactory.h
  ../include/SGFCPropertyValueType.h
  ../include/SGFCRealPropertyValue.h
  ../include/SGFCSimpleTextPropertyValue.h
  ../include/SGFCSinglePropertyValue.h
  ../include/SGFCStonePropertyValue.h
  ../include/SGFCTextPropertyValue.h
  ../include/SGFCTreeBuilder.h
  ../include/SGFCTypedefs.h
)
